/**
 * Created by my on 29.08.16.
 */

/**
 * The name generator is used to generate random names from two specified
 * dictionaries. The initial idea was taken from the docker source and is now spreading.
 */


/**
 * the left side of the alias string
 *
 * @type {string[]}
 */
var left = [
    "adaptable",
    "admiring",
    "adventurous",
    "affable",
    "affectionate",
    "agreeable",
    "ambitious",
    "amiable",
    "amicable",
    "amusing",
    "brave",
    "bright",
    "broad-minded",
    "calm",
    "careful",
    "charming",
    "communicative",
    "compassionate",
    "conscientious",
    "considerate",
    "convivial",
    "courageous",
    "courteous",
    "creative",
    "decisive",
    "determined",
    "diligent",
    "diplomatic",
    "discreet",
    "dynamic",
    "ecstatic",
    "easygoing",
    "emotional",
    "energetic",
    "enthusiastic",
    "exuberant",
    "fair-minded",
    "faithful",
    "fearless",
    "forceful",
    "frank",
    "friendly",
    "funny",
    "generous",
    "gentle",
    "good",
    "gregarious",
    "hard-working",
    "helpful",
    "honest",
    "humorous",
    "imaginative",
    "impartial",
    "independent",
    "intellectual",
    "intelligent",
    "intuitive",
    "inventive",
    "kind",
    "loving",
    "loyal",
    "modest",
    "neat",
    "nice",
    "nostalgic",
    "optimistic",
    "passionate",
    "patient",
    "persistent",
    "pioneering",
    "philosophical",
    "placid",
    "plucky",
    "polite",
    "powerful",
    "practical",
    "pro-active",
    "quick-witted",
    "quiet",
    "rational",
    "reliable",
    "reserved",
    "resourceful",
    "romantic",
    "self-confident",
    "self-disciplined",
    "sensible",
    "sensitive",
    "shy",
    "sincere",
    "sleepy",
    "sociable",
    "straightforward",
    "stoic",
    "sympathetic",
    "thirsty",
    "thoughtful",
    "tidy",
    "tough",
    "unassuming",
    "understanding",
    "versatile",
    "warmhearted",
    "willing",
    "witty"
];

/**
 * the right side of the alias string
 *
 * @type {string[]}
 */
var right = [
    "albattani",
    "allen",
    "almeida",
    "archimedes",
    "ardinghelli",
    "aryabhata",
    "austin",
    "babbage",
    "banach",
    "baracus",
    "bardeen",
    "bartik",
    "bassi",
    "bell",
    "berners-lee",
    "bhabha",
    "bhaskara",
    "blackwell",
    "bohr",
    "booth",
    "borg",
    "bose",
    "bowie",
    "boyd",
    "brahmagupta",
    "brattain",
    "brin",
    "brown",
    "carson",
    "chandrasekhar",
    "cobain",
    "coen",
    "colden",
    "cooper",
    "cori",
    "cray",
    "curie",
    "darwin",
    "davinci",
    "dijkstra",
    "dubinsky",
    "dude",
    "durden",
    "easley",
    "einstein",
    "elion",
    "engelbart",
    "euclid",
    "euler",
    "ewing",
    "fermat",
    "fermi",
    "feynman",
    "franklin",
    "galileo",
    "gates",
    "goldberg",
    "goldstine",
    "goldwasser",
    "golick",
    "goodall",
    "grohl",
    "hamilton",
    "hawking",
    "harrison",
    "hasselhoff",
    "heisenberg",
    "hendrix",
    "heyrovsky",
    "hodgkin",
    "hofstadter",
    "hoover",
    "hopper",
    "hugle",
    "hypatia",
    "jang",
    "jagger",
    "jennings",
    "jepsen",
    "joliot",
    "jones",
    "kalam",
    "kare",
    "keller",
    "kenobi",
    "khorana",
    "kilby",
    "kirch",
    "kirk",
    "knuth",
    "koothrappali",
    "kowalevski",
    "krekhov",
    "krueger",
    "kubrick",
    "lalande",
    "lamarr",
    "lasseter",
    "leakey",
    "leavitt",
    "lennon",
    "lichterman",
    "liskov",
    "lovelace",
    "lucas",
    "lumiere",
    "mahavira",
    "mayer",
    "mcCarthy",
    "mcCartney",
    "mcFly",
    "mcClintock",
    "mcLean",
    "mcNulty",
    "meitner",
    "meninsky",
    "mestorf",
    "minsky",
    "mirzakhani",
    "morgana",
    "morse",
    "murdock",
    "mulder",
    "musk",
    "newton",
    "nobel",
    "noether",
    "nolan",
    "northcutt",
    "noyce",
    "page",
    "panini",
    "pare",
    "parker",
    "pasteur",
    "payne",
    "perlman",
    "picard",
    "pike",
    "pinkman",
    "poincare",
    "poitras",
    "ptolemy",
    "raman",
    "ramanujan",
    "resig",
    "richards",
    "ride",
    "ritchie",
    "roentgen",
    "rosalind",
    "ryker",
    "saha",
    "sammet",
    "schiewe",
    "schimdt",
    "schorer",
    "scully",
    "seinfeld",
    "shannon",
    "shaw",
    "shirley",
    "shockley",
    "sinoussi",
    "skywalker",
    "snyder",
    "snowden",
    "solo",
    "spence",
    "spielberg",
    "stallman",
    "starr",
    "stinson",
    "stonebraker",
    "stroustrup",
    "swanson",
    "swartz",
    "swirles",
    "tarantino",
    "tesla",
    "thompson",
    "torvalds",
    "turing",
    "varahamihira",
    "vega",
    "visvesvaraya",
    "volhard",
    "wallowitz",
    "watzlawik",
    "wayne",
    "wescoff",
    "williams",
    "wilson",
    "wing",
    "wozniak",
    "wright",
    "yalow",
    "yonath"
];

// ---------------------------------------------
// - FUNCTIONS

/**
 * creates a random string from two sources to act as an alias
 *
 * @returns {string}
 */
function generate() {
    var leftSide = randomElement(left);
    var rightSide = randomElement(right);

    return `${leftSide} ${rightSide}`;
}

/**
 * helper method to extract a random array element
 *
 * @param arr
 * @returns {*}
 */
function randomElement(arr) {
    return arr[Math.floor(Math.random() * arr.length)];
}

// ---------------------------------------------
// - MODULE

module.exports = generate;